name: Upload File

on:
  Push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRECT_ACCESS_KEY: ${{secrets.AWS_SECRECT_ACCESS_KEY}}
        AWS_SESSION_TOKEN : ${{secrets.AWS_SESSION_TOKEN}}
        file-path: 'C:\Users\admin\Downloads\sm vita\Gitpractice\.github\workflows\app.py'

